vikhyatsingh123/Naruto-Shippuden

- index.html
Plz review my PR as soon as possible.
> New Card added of character Mitsuki

- index.html
> fix UI bug

- index.html
> Added character : Tsunade Senju : Hactoberfest

- index.html
> Added Shikadai Nara  : Hactoberfest

- index.html
I have added Choji-Akimichi character.
> Add Choji-Akimichi character

- index.html
> Added character :  Kakuzu ( Hactoberfest )

- index.html
> Rock Lee Added

- .vscode/settings.json
- about.html
- style.css
@vikhyatsingh123 Done Sir !
All cards of villains and heroes separated successfully :)
> Cards Added  successflly .

- index.html
Added Fugaku Character who is the father of Itachi and Sasuke and one of the most powerful Uchiha.
> Added Fugaku Card

- index.html
Added missing image and now character is in proper way
> updated Index.html

- index.html
The issue you mentioned in #271 has been fixed.
> Fixed navbar section which was going out of page

- index.html
hey @vikhyatsingh123  I have added a character Tsunade 
I know I am a bit late, Please make the merge ASAP
> added a charector Tsunade

- index.html
added katazu card please merge @vikhyatsingh123
> Added new Katazu card

- index.html
> Added hyperlink of GitHub profile

- index.html
> Added : Tatewaki Card

- index.html
this is my first time contributing thank you so much for this amazing tutorial <3
> added Kidomaru!

- index.html
> Added one new card 

- index.html
I have fixed the layout for the button as discussed in #668 and attaching snapshots also for the same.
Please review the same and merge the PR.
Best regards.
> change css styles of Scroll-to-top Button

- index.html
- style.css
previously looks like this
after update
> darkmode button margin

- style.css
Preventing the website to scroll in horizontal direction, making the overall website UI look good
> Turned off the horizontal scrolling of the website

- .vscode/settings.json
- style.css
The dark mode is not changing color correctly i corrected it
> darkmode error corrected

- style.css
Changes made
- Better Dark Mode colors to prevent eye straining
- Curved card border to give modern look
- removed card border outline to make it more clean
- better light mode color to go with them
- better text background
- clean and modern ui updated
> Changed UI of Website and Card borders

- index.html
> Add Kakuzu character

- index.html
Adding pain card to the repository
> Adding pain card

- style.css
Fixed the backface of character cards, Now text no longer overflows, makes page more responsive as well.
> fixed flip-card-back text overflow

- README.md
I hope the irony is appreciated
> Add space after sentence

- about.html
- style.css
Hi @vikhyatsingh123, In this PR I've done the following changes:-
- Changed the colors of the about card to the official colors used by the respective company(eg- Facebook, Instagram, GitHub, LinkedIn)
- Added border radius to the about card and
- removed the repeating internal CSS for the footer on the about page.
I am attaching the before and after screenshot
Before:-
After:- 
Hope you find the changes good to merge.
Thank You!
> styles: changed colors and added border-radius to socials about-card

- index.html
- style.css
@vikhyatsingh123  I think someone have done the footer section responsive, so I have added  social icons. #953 issue resolve. Please merge this under Hacktoberfest. Thank you.
> social icons added

- index.html
I have added the image of shisui character as it was not displaying on the card.
> Shisui image added

- index.html
> Shino Aburame added

- index.html
This PR is to add the card about Shizune. Please review
> Added Shizune's card

- index.html
@vikhyatsingh123 
Kindly check now, added shisui uchiha
here is the ss:
> Shisui Uchiha added

- index.html
This PR is to add information about Karin Uzumaki
> Added card fro Karin

- index.html
- lazyload.js
I added lazy loading functionality, in html and js. This change will make website load 40% faster at least. I only applied this to character cards feel free to include other elements. P.s this change will require a change to the readme file, the part about how to contribute to the project. Thank you
> Lazy loading Images

- README.md
- lazyload.js
After my lazy loading PR was accepted I realised more changes are required so other can take advantage of lazy loading moving forward. So I edited readme and improved the UX for lazy loading. Thank you.
> Lazy loading followup

- contact.css
- contact.html
- index.html
I hope u like my work and  merge it in to your project
> added a cool modern naruto glass contactform

- index.html
So basically the recents commits brought some issues in the landing page as characters were being shown below the footer so I handled that and made some changes in the code as well as I added some more characters to it to make it more good . However this repo is so beginner friendly for the new user to learn ......
> Aligned the updated code properly and added more 5-6 characters 

- index.html
The image source of Princess Kasumi was wrong which has been fixed in this PR.
> Fixed Princess Kasumi Card Image not being displayed

- index.html
- style.css
i have make name clickable in the footer
> link added

- index.css
- index.html
- switch-toggle.js
This PR is meant for Issue #1085 which adds a toggle bar that allows a user to easily switch between Heroes and Villain tabs. (Note: I made the GIF prior to switching the Good and Evil options to Heroes and Villains" to better align with your original request.
On each card div simply add the class 'good', 'evil' or leave it the same. If you add 'good' it will display with heroes and 'evil' will display villains. If you do not choose between good and evil (add neither classes), the character is considered neutral and is displayed with both groups. 
Please let me know if this adds value to your project. I look forward to working with you in the future. 
Example Hero: 
```
<div class="flip-card good">
<div class="flip-card-inner">
<div class="flip-card-front">
<h2 class="card-title">Naruto …
```
> Issue# 1085 Separate Hero's and Villains

- index.html
- style.css
fixes #1089 
HERE I REMOVE THE TOP HIGHT OF IMAGE AND ADJUST THE HIGHT AND WIDTH of the image
> FIX THE SCALE ISSU

- README.md
This PR was created to update the Readme.md file to include instructions on how to use the good/evil classes created from the Issue within the subject line. 
Thanks again for the chance to contribute and I hope you have a great day!
> Updated ReadMe Issue# 1085 Separate Hero's and Villains

- index.html
Added 4 cards and did changes with the images where there where small issue that for some character the image was not working. So I kept the thing which would work perfectly with the website
> Added few cards and images 

- about.html
- style.css
> about page

- style.css
previously the search_button was appearing on the NARUTO word, and now it is fixed
> fixed the search_button position

- index.css
- index.html
I have added the ninja naruto text in only on the characters name 
if you want to add anywhere else let me know
#1075 PR
> added the ninja-naruto text

- index.html
Added new card of name kawakii
> ADD NEW CARD

- index.html
- translate.css
- translate.js
closes #1140 
[Screencast from 26-10-23 08:52:00 PM IST.webm](https://github.com/vikhyatsingh123/Naruto-Shippuden/assets/104543751/38ab7d47-0b8a-4df5-890c-e47f21c2f5be)
> translate added

- contact.html
> favicon added

- index.html
> update a card

- about.html
> naruto redirection fixed

- contact.html
> navbar added

- index.html
update 1 more card please merge it
>  update another card

- index.html
close : #1170
Fixed "Anko" card width and give flip effect.
> fixed "Anko" card

- index.css
- style.css
hey @vikhyatsingh123 
I fixed the overlapping for most of devices 
if still missing something then please let me know
Thank You...!:)
> Fixed overlapping footer

- index.html
Added Son Goku Card to the main file index.html
> Added Son Goku Card

- contact.css
- contact.html
- contact.js
Added popup of Both Error and Success insted of simple HTML text.
Impoved visibility of Form...
> Contact naruto

- contact.css
- contact.html
- index.css
- index.html
- translate.css
**Initial Looks and bug as Google option was shown while changing language....**
<br><br><br><br>
<br><br><br><br><br>
**Final Look**
Now google option doesn't popup as well as button matches with Dark mode button ....
> Changed Language Button UI

- index.html
Removed all repeated cards from index.html.
fixed : #1182 
Contributing under : Codepeak 2023
> Removed all repeated cards

- about.html
> [BUG]: Contact page added

- index.html
> [BUG]: Choji picture update.

- style.css
> Nav bar fixed

- index.html
This card was already moved by someone in the previous update to the branch everything left was this comment.
Fix issue #1195
> [BUG] Gojo card removed.

- css/style.css
- css/translate.css
#1214 this issue which i raised a few days ago has been solved labesl requested:  open-source; hactoberfest-accepted please review this @vikhyatsingh123
> solved the issue #1214 coinciding of select language tab and play\pause button fixed .

- css/contact.css
- css/index.css
- css/style.css
- index.html
Play button was too right, making it look weird like embedded into wall, i gave it margin and is responsive too
> Play button got margin

- css/style.css
- index.html
The style of the anchor tags is improved. Also the font of the anchor tags are changed.
> Styling of the anchors tags improved

- .github/workflows/static.yml
- index.html
I have made changes to the static.yml by updating it to the latest version of github actions because it was outdated and created error while you have merged my request. Please review it and merge the pull request.
> Made changes to the static.yml

- index.html
I’ve added a new hero card for Hinata Hyuga to index.html. Please review it. Let me know if any changes are needed. Thank you!
> Added Hero Card for Hinata Hyuga
